// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "ximage_inverter.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XImage_inverter_CfgInitialize(XImage_inverter *InstancePtr, XImage_inverter_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XImage_inverter_Start(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL) & 0x80;
    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XImage_inverter_IsDone(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XImage_inverter_IsIdle(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XImage_inverter_IsReady(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XImage_inverter_EnableAutoRestart(XImage_inverter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XImage_inverter_DisableAutoRestart(XImage_inverter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL, 0);
}

void XImage_inverter_Set_ptrInput(XImage_inverter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_PTRINPUT_DATA, Data);
}

u32 XImage_inverter_Get_ptrInput(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_PTRINPUT_DATA);
    return Data;
}

void XImage_inverter_Set_ptrOutput(XImage_inverter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_PTROUTPUT_DATA, Data);
}

u32 XImage_inverter_Get_ptrOutput(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_PTROUTPUT_DATA);
    return Data;
}

void XImage_inverter_Set_pixelsN(XImage_inverter *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_PIXELSN_DATA, Data);
}

u32 XImage_inverter_Get_pixelsN(XImage_inverter *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_PIXELSN_DATA);
    return Data;
}

void XImage_inverter_InterruptGlobalEnable(XImage_inverter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_GIE, 1);
}

void XImage_inverter_InterruptGlobalDisable(XImage_inverter *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_GIE, 0);
}

void XImage_inverter_InterruptEnable(XImage_inverter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_IER);
    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_IER, Register | Mask);
}

void XImage_inverter_InterruptDisable(XImage_inverter *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_IER);
    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_IER, Register & (~Mask));
}

void XImage_inverter_InterruptClear(XImage_inverter *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImage_inverter_WriteReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_ISR, Mask);
}

u32 XImage_inverter_InterruptGetEnabled(XImage_inverter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_IER);
}

u32 XImage_inverter_InterruptGetStatus(XImage_inverter *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XImage_inverter_ReadReg(InstancePtr->Axilites_BaseAddress, XIMAGE_INVERTER_AXILITES_ADDR_ISR);
}

