// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ptrInput
//        bit 31~0 - ptrInput[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of ptrOutput
//        bit 31~0 - ptrOutput[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of pixelsN
//        bit 31~0 - pixelsN[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XIMAGE_INVERTER_AXILITES_ADDR_AP_CTRL        0x00
#define XIMAGE_INVERTER_AXILITES_ADDR_GIE            0x04
#define XIMAGE_INVERTER_AXILITES_ADDR_IER            0x08
#define XIMAGE_INVERTER_AXILITES_ADDR_ISR            0x0c
#define XIMAGE_INVERTER_AXILITES_ADDR_PTRINPUT_DATA  0x10
#define XIMAGE_INVERTER_AXILITES_BITS_PTRINPUT_DATA  32
#define XIMAGE_INVERTER_AXILITES_ADDR_PTROUTPUT_DATA 0x18
#define XIMAGE_INVERTER_AXILITES_BITS_PTROUTPUT_DATA 32
#define XIMAGE_INVERTER_AXILITES_ADDR_PIXELSN_DATA   0x20
#define XIMAGE_INVERTER_AXILITES_BITS_PIXELSN_DATA   32

